config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :name_symbols
  root to: "elements#index"
  resources :elements
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/element.rb
class Element < ApplicationRecord
  validates_uniqueness_of :name, :symbol, :atomic_mass, :atomic_number
  validates :name, presence: true, format: { with: /\A[a-z\-' ]+\z/i }
  validates :symbol, presence: true, format: { with: /\A[a-z\-' ]+\z/i }
  validates :atomic_number, presence: true
  validates :atomic_mass, presence: true
  def name_symbol
    "#{name} - #{symbol}"
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :name_symbol
end

app/models/name_symbol.rb
class NameSymbol < ApplicationRecord
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: %i[ show edit update destroy ]

  # GET /elements or /elements.json
  def index
    @elements = Element.all
  end

  # GET /elements/1 or /elements/1.json
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  # POST /elements or /elements.json
  def create
    @element = Element.new(element_params)

    respond_to do |format|
      if @element.save
        format.html { redirect_to element_url(@element), notice: "Element was successfully created." }
        format.json { render :show, status: :created, location: @element }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elements/1 or /elements/1.json
  def update
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to element_url(@element), notice: "Element was successfully updated." }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1 or /elements/1.json
  def destroy
    @element.destroy!

    respond_to do |format|
      format.html { redirect_to elements_url, notice: "Element was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def element_params
      params.require(:element).permit(:name, :symbol, :atomic_number, :atomic_mass)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy!

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:group_number, :group_name)
    end
end

app/controllers/name_symbols_controller.rb
class NameSymbolsController < ApplicationController
  before_action :set_name_symbol, only: %i[ show edit update destroy ]

  # GET /name_symbols or /name_symbols.json
  def index
    @name_symbols = NameSymbol.all
  end

  # GET /name_symbols/1 or /name_symbols/1.json
  def show
  end

  # GET /name_symbols/new
  def new
    @name_symbol = NameSymbol.new
  end

  # GET /name_symbols/1/edit
  def edit
  end

  # POST /name_symbols or /name_symbols.json
  def create
    @name_symbol = NameSymbol.new(name_symbol_params)

    respond_to do |format|
      if @name_symbol.save
        format.html { redirect_to name_symbol_url(@name_symbol), notice: "Name symbol was successfully created." }
        format.json { render :show, status: :created, location: @name_symbol }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @name_symbol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /name_symbols/1 or /name_symbols/1.json
  def update
    respond_to do |format|
      if @name_symbol.update(name_symbol_params)
        format.html { redirect_to name_symbol_url(@name_symbol), notice: "Name symbol was successfully updated." }
        format.json { render :show, status: :ok, location: @name_symbol }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @name_symbol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /name_symbols/1 or /name_symbols/1.json
  def destroy
    @name_symbol.destroy!

    respond_to do |format|
      format.html { redirect_to name_symbols_url, notice: "Name symbol was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name_symbol
      @name_symbol = NameSymbol.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def name_symbol_params
      params.require(:name_symbol).permit(:name_of_element, :symbo_of_element)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/name_symbols_helper.rb
module NameSymbolsHelper
end

app/views/elements/_element.html.erb
<div id="<%= dom_id element %>">
  <!--
  <p>
    <strong>Name:</strong>
    <%= element.name %>
  </p>

  <p>
    <strong>Symbol:</strong>
    <%= element.symbol %>
  </p>
  -->

  <p>
    <strong>Name - Symbol: </strong>
    <%= element.name_symbol %>
  </p>

  <p>
    <strong>Atomic Number:</strong>
    <%= element.atomic_number %>
  </p>

  <p>
    <strong>Atomic Mass:</strong>
    <%= element.atomic_mass %>
  </p>

</div>

app/views/elements/_form.html.erb
<%= form_with(model: element) do |form| %>
  <% if element.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
        <% element.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :symbol, style: "display: block" %>
    <%= form.text_field :symbol %>
  </div>

  <div>
    <%= form.label :atomic_number, style: "display: block" %>
    <%= form.number_field :atomic_number %>
  </div>

  <div>
    <%= form.label :atomic_mass, style: "display: block" %>
    <%= form.text_field :atomic_mass %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Editing element</h1>

<%= render "form", element: @element %>

<br>

<div>
  <%= link_to "Show this element", @element %> |
  <%= link_to "Back to elements", elements_path %>
</div>

app/views/elements/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Elements</h1>

<div id="elements">
  <% @elements.each do |element| %>
    <%= render element %>
    <p>
      <%= link_to "Show this element", element %>
    </p>
  <% end %>
</div>

<%= link_to "New element", new_element_path %>

app/views/elements/new.html.erb
<h1>New element</h1>

<%= render "form", element: @element %>

<br>

<div>
  <%= link_to "Back to elements", elements_path %>
</div>

app/views/elements/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @element %>

<div>
  <%= link_to "Edit this element", edit_element_path(@element) %> |
  <%= link_to "Back to elements", elements_path %>

  <%= button_to "Destroy this element", @element, method: :delete %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :group_number, style: "display: block" %>
    <%= form.number_field :group_number %>
  </div>

  <div>
    <%= form.label :group_name, style: "display: block" %>
    <%= form.text_field :group_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p>
    <strong>Group Number:</strong>
    <%= group.group_number %>
  </p>

  <p>
    <strong>Group Name:</strong>
    <%= group.group_name %>
  </p>

</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Groups</h1>

<div id="groups">
  <% @groups.each do |group| %>
    <%= render group %>
    <p>
      <%= link_to "Show this group", group %>
    </p>
  <% end %>
</div>

<%= link_to "New group", new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExChemist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/name_symbols/_form.html.erb
<%= form_with(model: name_symbol) do |form| %>
  <% if name_symbol.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(name_symbol.errors.count, "error") %> prohibited this name_symbol from being saved:</h2>

      <ul>
        <% name_symbol.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name_of_element, style: "display: block" %>
    <%= form.text_field :name_of_element %>
  </div>

  <div>
    <%= form.label :symbo_of_element, style: "display: block" %>
    <%= form.text_field :symbo_of_element %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/name_symbols/_name_symbol.html.erb
<div id="<%= dom_id name_symbol %>">
  <p>
    <strong>Name of Element:</strong>
    <%= name_symbol.name_of_element %>
  </p>

  <p>
    <strong>Symbol of Element:</strong>
    <%= name_symbol.symbo_of_element %>
  </p>

</div>

app/views/name_symbols/edit.html.erb
<h1>Editing name symbol</h1>

<%= render "form", name_symbol: @name_symbol %>

<br>

<div>
  <%= link_to "Show this name symbol", @name_symbol %> |
  <%= link_to "Back to name symbols", name_symbols_path %>
</div>

app/views/name_symbols/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Name symbols</h1>

<div id="name_symbols">
  <% @name_symbols.each do |name_symbol| %>
    <%= render name_symbol %>
    <p>
      <%= link_to "Show this name symbol", name_symbol %>
    </p>
  <% end %>
</div>

<%= link_to "New name symbol", new_name_symbol_path %>

app/views/name_symbols/new.html.erb
<h1>New name symbol</h1>

<%= render "form", name_symbol: @name_symbol %>

<br>

<div>
  <%= link_to "Back to name symbols", name_symbols_path %>
</div>

app/views/name_symbols/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @name_symbol %>

<div>
  <%= link_to "Edit this name symbol", edit_name_symbol_path(@name_symbol) %> |
  <%= link_to "Back to name symbols", name_symbols_path %>

  <%= button_to "Destroy this name symbol", @name_symbol, method: :delete %>
</div>